### ISSUE TITLE
Missing Validator dependency

### ISSUE THREAD

**Issue by eeviefogrot** [bkonkle/nakago#125]
## Bug description

- Would you like to work on a fix? [y/n]

## To Reproduce

1. Make a project using the steps from the nakago site
2. run it
3. go to /username

## Expected behavior

Response should be:
```json
{
  "code": 200,
  "username": "(anonymous)"
}
```

## Screenshots

![image](https://github.com/user-attachments/assets/6a0d2d47-35ca-45d6-825a-cac7fafe4e65)

## Environment

- OS: Windows 11
- nakago version: 0.23

**Comment by bkonkle** [comment]
Hi! Thank you for the report! I'll take a look and find a fix.

**Comment by bkonkle** [comment]
Okay, I was able to reproduce and I found some places where the tutorial and template needed to be updated. Thank you for the heads-up!

https://github.com/bkonkle/nakago/pull/126

One quick note - make sure you're using a real OAuth provider for the `config.toml` settings here:

```toml
[auth]
url = "https://simple-dev.oauth-service.com"
```

You might also need to add an `audience` setting (with Auth0, for example):

```toml
[auth]
url = "https://simple-dev.oauth-service.com"
audience = "localhost"
```

Here's what my results look like:

![image](https://github.com/user-attachments/assets/f36b91a3-7398-4ad6-92a5-631c844aed3c)
